In [74]:
import cv2
import numpy as np


In [75]:
def show_img(img, name="img name"):
    cv2.imshow(name, img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()


In [76]:
canvas = np.zeros((800, 800, 3))
# show_img(canvas, "canvas")


# Drawing Line

## cv2.line(matrix, (x1, y1), (x2, y2), (B, G, R), thickness)


In [77]:
line = cv2.line(canvas, (100, 100), (300, 100), (255, 0, 255), 1)
# show_img(line, "line with thickness 1")


In [78]:
line = cv2.line(canvas, (100, 150), (300, 150), (255, 255, 255), 10)
# show_img(line, "line with thickness 10")


# Rectangle

## cv2.rectangle(matrix, (x1, y1), (x2, y2), (B, G, R), thickness)


In [79]:
rectangle = cv2.rectangle(canvas, (100, 200), (450, 450), (255, 255, 0), 1)
# show_img(rectangle, "rectangle with border with 1")


In [80]:
rectangle = cv2.rectangle(canvas, (500, 200), (750, 450), (0, 255, 0), 10)
# show_img(rectangle, "rectangle with border 10")


In [81]:
rectangle = cv2.rectangle(canvas, (100, 500), (450, 750), (0, 255, 0), -1)
# show_img(rectangle, "rectangle with fill")


# Circle

## cv2.circle(matrix, (x, y), r, (B, G, R), thickness)


In [82]:
circle = cv2.circle(canvas, (250, 325), 100, (0, 0, 255), 1)
# show_img(circle, "circle with border 1")


In [83]:
circle = cv2.circle(canvas, (625, 325), 100, (0, 0, 255), 10)
# show_img(circle, "circle with border 10")


In [84]:
circle = cv2.circle(canvas, (275, 625), 100, (0, 0, 255), -1)
# show_img(circle, "circle with fill")


# Arrowed Line

## cv2.arrowedLine(matrix, (x1, y1), (x2, y2), (B, G, R), thickness)


In [85]:
arrowedLine = cv2.arrowedLine(canvas, (100, 775), (300, 775), (255, 0, 0), 1)
# show_img(arrowedLine, "arrowed line with border 1")


In [86]:
arrowedLine = cv2.arrowedLine(canvas, (350, 775), (600, 775), (255, 0, 0), 10)
# show_img(arrowedLine, "arrowed line with border 10")


# poly line


In [87]:
pts = np.array([[250, 5], [220, 80], [280, 80]], dtype=np.int32)
print(pts)
pts = pts.reshape((-1, 1, 2))
print(pts)

polyLine = cv2.polylines(canvas, [pts], True, (123, 123, 123), 3)
show_img(polyLine, "poly line with 3 pointes")


[[250   5]
 [220  80]
 [280  80]]
[[[250   5]]

 [[220  80]]

 [[280  80]]]


In [88]:
pts = np.array([[111,645],[222,678],[333,453],[444,567],[555,344],[666,234],], dtype=np.int32)
print(pts)
pts = pts.reshape((-1, 1, 2))
print(pts)

polyLine = cv2.polylines(canvas, [pts], True, (0, 123, 123), 3)
show_img(polyLine, "poly line with multi pointes")


[[111 645]
 [222 678]
 [333 453]
 [444 567]
 [555 344]
 [666 234]]
[[[111 645]]

 [[222 678]]

 [[333 453]]

 [[444 567]]

 [[555 344]]

 [[666 234]]]
