In [1]:
import numpy as np

print(np.__version__)


1.22.1


In [2]:
import cv2


In [3]:
def show_img(img, name="img"):
    cv2.imshow(name, img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()


# single row


In [4]:
arr_1row = np.array([1, 2, 3, 4, 5, 6, 7])
arr_1row


array([1, 2, 3, 4, 5, 6, 7])

# multiple cols


In [5]:
arr_nd_col = np.array([[1, 2], [2, 2], [3, 2]])
arr_nd_col


array([[1, 2],
       [2, 2],
       [3, 2]])

# 1d Array


In [6]:
arr_1d = np.array([1, 2, 3, 4, 5, 6, 7])
arr_1d


array([1, 2, 3, 4, 5, 6, 7])

# 2d Array


In [7]:
arr_2d = np.array([[1, 2, 3, 4, 5, 6, 7], [1, 2, 3, 4, 5, 6, 7]])
arr_2d


array([[1, 2, 3, 4, 5, 6, 7],
       [1, 2, 3, 4, 5, 6, 7]])

# multi dimension


In [8]:
arr_nd = np.array(
    [
        [(1, 2, 3), (4, 5, 6, 7)],
        [(1, 2, 3, 4), (5, 6, 7)],
        [(1, 2, 3), (4, 5, 6, 7)],
        [(1, 2, 3, 4), (5, 6, 7)],
        [(1, 2, 3), (4, 5, 6, 7)],
        [(1, 2, 3, 4), (5, 6, 7)],
    ],
    dtype=object,
)
arr_nd


array([[(1, 2, 3), (4, 5, 6, 7)],
       [(1, 2, 3, 4), (5, 6, 7)],
       [(1, 2, 3), (4, 5, 6, 7)],
       [(1, 2, 3, 4), (5, 6, 7)],
       [(1, 2, 3), (4, 5, 6, 7)],
       [(1, 2, 3, 4), (5, 6, 7)]], dtype=object)

# Zeros


In [9]:
zeroes = np.zeros((3, 3), dtype="uint8")
zeroes


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=uint8)

# Ones


In [10]:
ones = np.ones((3, 3), dtype="uint8")
ones


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=uint8)

# Full


In [11]:
full = np.full((3, 3), 5, dtype="uint8")
full


array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]], dtype=uint8)

# eye


In [12]:
eye = np.eye(5, dtype="uint8")
eye


array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=uint8)

# Random


In [13]:
range = np.arange(1, 100, 1, dtype="uint8")
range


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
      dtype=uint8)

# Line Space


In [14]:
line_space = np.linspace(0, 100, 10)
line_space


array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

# Random


In [15]:
rand = np.random.rand()
rand


0.3164197236267673

In [16]:
rand = np.random.rand(2, 5)
rand


array([[0.69019487, 0.34166503, 0.11492504, 0.19314693, 0.576005  ],
       [0.86436938, 0.05023721, 0.22674921, 0.61090267, 0.88811438]])

In [17]:
rand = np.random.rand(2, 3, 4)
rand


array([[[0.32581869, 0.71404231, 0.82068141, 0.16679343],
        [0.38208462, 0.03807017, 0.18506756, 0.95189046],
        [0.2858344 , 0.28064612, 0.1872689 , 0.05938755]],

       [[0.35839101, 0.91090718, 0.2269427 , 0.31826846],
        [0.57637085, 0.24901755, 0.49137123, 0.68827042],
        [0.33972946, 0.08019152, 0.91485487, 0.39589444]]])

## with in range 100


In [18]:
rand = np.random.rand() * 100
rand


38.758936344687456

In [19]:
rand = np.random.rand(2, 3, 4) * 100
rand


array([[[78.24427782, 16.88726039, 84.56019215, 12.72860339],
        [75.27791406,  0.73283086, 29.11050833,  8.04314712],
        [82.81998753, 46.31870128, 56.17176428, 96.56316644]],

       [[32.48030139, 32.09296781, 24.55868974, 14.44569945],
        [81.35053787, 94.54067156, 93.38550475, 65.35693843],
        [61.12317836, 25.77707153, 30.22402074,  5.3799761 ]]])

In [20]:
rand = np.random.randint(0, 255, (3, 28, 28))
rand


array([[[194, 169, 129, ..., 205,  60,  32],
        [ 33, 112, 123, ..., 227,  57, 134],
        [204,   3,  85, ..., 198, 193,  30],
        ...,
        [184, 117,  18, ..., 176, 135,  85],
        [  8, 154,  82, ..., 191, 195, 156],
        [ 38,  89,   5, ..., 201, 225,   5]],

       [[ 54,  25,  43, ...,  92,  36,  55],
        [ 76, 232,  25, ...,  74, 172,  50],
        [ 91,  41, 142, ..., 202, 249,  27],
        ...,
        [117, 145, 193, ..., 196,  14,  15],
        [170, 126, 106, ..., 210,  87,  82],
        [ 74, 188,  95, ...,  21, 204,  89]],

       [[ 42,   7,   8, ..., 193, 162, 164],
        [143, 216, 228, ..., 187, 204,  80],
        [169,  31, 239, ...,  86, 143, 164],
        ...,
        [183, 112,  17, ..., 233, 253,   0],
        [ 47, 151,  86, ..., 122, 164, 143],
        [243,  82, 173, ...,  69,  53,  58]]])

# shape


In [21]:
rand = np.random.randint(0, 255, (3, 28, 28))
rand.shape


(3, 28, 28)

# size

=> total elements


In [22]:
rand = np.random.randint(0, 255, (3, 28, 28))
rand.size


2352

# data type


In [23]:
rand = np.random.randint(0, 255, (3, 28, 28), dtype="uint8")
rand.dtype


dtype('uint8')

In [24]:
rand = np.random.randint(0, 255, (3, 28, 28))
rand = rand.astype(float)
rand.dtype


dtype('float64')

# Array merge


In [25]:
arr1 = np.array([[1, 2, 3, 4, 5, 6, 7], [1, 2, 3, 4, 5, 6, 7]])
arr2 = np.array([[1, 2, 3, 4, 5, 6, 7], [1, 2, 3, 4, 5, 6, 7]])
arr = arr1 + arr2
arr


array([[ 2,  4,  6,  8, 10, 12, 14],
       [ 2,  4,  6,  8, 10, 12, 14]])

In [26]:
arr1 = np.array([[1, 2, 3, 4, 5, 6, 7], [1, 2, 3, 4, 5, 6, 7]])
arr = arr1 + 20
arr


array([[21, 22, 23, 24, 25, 26, 27],
       [21, 22, 23, 24, 25, 26, 27]])

In [27]:
arr1 = np.array([1, 2, 3, 4, 5, 6, 7])
arr2 = np.array([1, 2, 3, 4, 5, 6, 7])
arr = arr1 - arr2
arr


array([0, 0, 0, 0, 0, 0, 0])

In [28]:
arr1 = np.array([1, 2, 3, 4, 5, 6, 7])
arr = arr1 - 4
arr


array([-3, -2, -1,  0,  1,  2,  3])

In [29]:
arr1 = np.array([1, 2, 3, 4, 5, 6, 7])
arr2 = np.array([1, 2, 3, 4, 5, 6, 7])
arr = arr1 * arr2
arr


array([ 1,  4,  9, 16, 25, 36, 49])

In [30]:
arr1 = np.array([1, 2, 3, 4, 5, 6, 7])
arr = arr1 * 5
arr


array([ 5, 10, 15, 20, 25, 30, 35])

In [31]:
arr1 = np.array([1, 2, 3, 4, 5, 6, 7])
arr2 = np.array([1, 2, 3, 4, 5, 6, 7])
arr = arr1 / arr2
arr


array([1., 1., 1., 1., 1., 1., 1.])

In [32]:
arr1 = np.array([1, 2, 3, 4, 5, 6, 7])
arr = arr1 / 5
arr


array([0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4])

# Min-Max


In [33]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr.min()


1

In [34]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr.max()


7

# indexing


In [35]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr[2]


3

In [36]:
arr = np.array([[1, 2, 3, 4, 5, 6, 7], [1, 2, 3, 4, 5, 6, 7]])
arr[:, 2]


array([3, 3])

In [37]:
arr = np.array([[1, 2, 3, 4, 5, 6, 7], [1, 2, 3, 4, 5, 6, 7]])
arr[1, :]


array([1, 2, 3, 4, 5, 6, 7])

In [38]:
arr = np.array([[1, 2, 3, 4, 5, 6, 7], [1, 2, 3, 4, 5, 6, 7]])
arr[1, 4:]


array([5, 6, 7])

In [39]:
arr = np.array([[1, 2, 3, 4, 5, 6, 7], [1, 2, 3, 4, 5, 6, 7]])
arr[1, 2:4]


array([3, 4])

In [40]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr[2:4]


array([3, 4])

# Reverse


In [41]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr[::-1]


array([7, 6, 5, 4, 3, 2, 1])

# Reshape


In [42]:
arr = np.array([[1, 2, 3, 4, 5, 6, 7], [1, 2, 3, 4, 5, 6, 7]])
print(arr.shape)
arr = arr.reshape(7, 2)
arr


(2, 7)


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [43]:
arr = np.array([[1, 2, 3, 4, 5, 6, 7], [1, 2, 3, 4, 5, 6, 7]])
print(arr.shape)
arr = arr.reshape(14, 1)
arr


(2, 7)


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [44]:
arr = np.array([[1, 2, 3, 4, 5, 6, 7], [1, 2, 3, 4, 5, 6, 7]])
print(arr.shape)
arr = arr.reshape(14)
arr


(2, 7)


array([1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7])

# Append


In [45]:
arr = np.array([[1, 2, 3, 4, 5, 6, 7], [1, 2, 3, 4, 5, 6, 7]])
arr = np.append(arr, 80)
arr


array([ 1,  2,  3,  4,  5,  6,  7,  1,  2,  3,  4,  5,  6,  7, 80])

# Delete


In [46]:
arr = np.array([[1, 2, 3, 4, 5, 6, 7], [1, 2, 3, 4, 5, 6, 7]])
arr = np.delete(arr, 1)
arr


array([1, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7])

# Flatten


In [47]:
arr = np.array([[1, 2, 3, 4, 5, 6, 7], [1, 2, 3, 4, 5, 6, 7]])
arr = arr.ravel()
arr


array([1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7])

In [48]:
arr = np.array([[1, 2, 3, 4, 5, 6, 7], [1, 2, 3, 4, 5, 6, 7]])
arr = arr.flatten()
arr


array([1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7])

In [49]:
rand = np.random.randint(0, 255, (3, 28, 28))
print(rand.shape)
rand = rand.flatten()
print(rand.shape)
rand


(3, 28, 28)
(2352,)


array([140, 204, 254, ..., 161,  70, 171])

# Concatenation


In [50]:
arr1 = np.array([1, 2, 3, 4, 5, 6, 7])
arr2 = np.array([1, 2, 3, 4, 5, 6, 7])
arr = np.concatenate((arr1, arr2))
arr


array([1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7])

# transpose

rows to cols cols to rows


In [51]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.transpose()


array([[1, 4],
       [2, 5],
       [3, 6]])

# Copy


In [52]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr_copy = arr
arr_copy


array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr_copy = np.copy(arr)
arr_copy


array([[1, 2, 3],
       [4, 5, 6]])

# Simple Image


In [54]:
img = np.zeros((300, 300))
img[:, :] = 100
img = img[:, :] + 10
img[50:250, 50:250] = 255
# show_img(img)
cv2.imwrite("sample.jpg", img)


True