In [19]:
import numpy as np
print(np.__version__)

1.22.1


#### single row

In [20]:
arr_1row = np.array([1,2,3,4,5,6,7])
arr_1row

array([1, 2, 3, 4, 5, 6, 7])

#### multiple cols

In [21]:
arr_nd_col = np.array([[1,2],[2,2],[3,2]])
arr_nd_col

array([[1, 2],
       [2, 2],
       [3, 2]])

1d Array

In [22]:
arr_1d = np.array([1,2,3,4,5,6,7])
arr_1d

array([1, 2, 3, 4, 5, 6, 7])

#### 2d Array

In [23]:
arr_2d = np.array([[1,2,3,4,5,6,7],[1,2,3,4,5,6,7]])
arr_2d

array([[1, 2, 3, 4, 5, 6, 7],
       [1, 2, 3, 4, 5, 6, 7]])

#### multi dimension

In [24]:
arr_nd = np.array([
    [(1,2,3),(4,5,6,7)],
    [(1,2,3,4),(5,6,7)],
    [(1,2,3),(4,5,6,7)],
    [(1,2,3,4),(5,6,7)],
    [(1,2,3),(4,5,6,7)],
    [(1,2,3,4),(5,6,7)]], dtype=object)
arr_nd

array([[(1, 2, 3), (4, 5, 6, 7)],
       [(1, 2, 3, 4), (5, 6, 7)],
       [(1, 2, 3), (4, 5, 6, 7)],
       [(1, 2, 3, 4), (5, 6, 7)],
       [(1, 2, 3), (4, 5, 6, 7)],
       [(1, 2, 3, 4), (5, 6, 7)]], dtype=object)

#### Zeros

In [25]:
zeroes = np.zeros((3,3), dtype='uint8')
zeroes

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=uint8)

#### Ones

In [26]:
ones = np.ones((3,3), dtype='uint8')
ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=uint8)

#### Full

In [27]:
full = np.full((3,3),5, dtype='uint8')
full

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]], dtype=uint8)

#### eye

In [30]:
eye = np.eye(5, dtype='uint8')
eye

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=uint8)

#### Random

In [33]:
range = np.arange(1,100,1,dtype='uint8')
range

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
      dtype=uint8)

#### Line Space

In [35]:
line_space = np.linspace(0,100,10)
line_space

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

#### Random

In [39]:
rand = np.random.rand()
rand

0.8195137450847809

In [40]:
rand = np.random.rand(2,5)
rand

array([[0.72254755, 0.08296081, 0.59556377, 0.28562018, 0.06848048],
       [0.26144583, 0.1776503 , 0.93510367, 0.29408744, 0.57622068]])

In [43]:
rand = np.random.rand(2,3,4)
rand

array([[[0.6758909 , 0.22598328, 0.78870633, 0.19151682],
        [0.72120254, 0.66547089, 0.50886762, 0.42591394],
        [0.9651436 , 0.16266547, 0.53930913, 0.26360409]],

       [[0.83292802, 0.70895061, 0.2914555 , 0.12690473],
        [0.88009382, 0.02787338, 0.75155018, 0.59152895],
        [0.51944918, 0.84017583, 0.07104437, 0.72001866]]])

with in range 100

In [44]:
rand = np.random.rand()*100
rand

89.14557273719853

In [45]:
rand = np.random.rand(2,3,4)*100
rand

array([[[19.70563493, 29.94604331, 76.27721141, 14.10250279],
        [76.5394571 , 12.98286629, 63.54631544, 19.93449755],
        [83.61918309, 90.52513179, 30.38972797, 83.5841908 ]],

       [[92.5941097 , 82.66180551, 22.71469046, 50.68809773],
        [64.92166753, 87.11506558, 92.92527516, 89.06840617],
        [ 6.09079303, 32.29156316, 91.36318777, 84.04152893]]])

In [55]:
rand = np.random.randint(0,255,(3,28,28))
rand

array([[[ 71, 243, 149, ..., 210, 132,  74],
        [ 49,  85, 171, ..., 122,  26, 213],
        [ 86, 212,   0, ..., 138, 221,  96],
        ...,
        [  1, 227, 108, ...,  62, 238,  17],
        [ 32, 214,   7, ..., 203, 173,  36],
        [206, 161,  22, ...,  94, 108,   8]],

       [[125, 129,  96, ...,  53, 149, 165],
        [ 29, 176,  49, ...,  61,  24, 168],
        [226,  18, 244, ..., 154, 186, 133],
        ...,
        [ 98, 172, 151, ..., 102, 133, 108],
        [ 20,  37,  78, ...,   3, 210, 178],
        [100, 139, 232, ...,  41,  21, 209]],

       [[ 57,  69, 211, ...,  91,  25, 176],
        [ 53, 206, 128, ..., 238,   0,  76],
        [160,  16,  15, ...,   1, 135, 146],
        ...,
        [174,  18, 207, ..., 120, 166, 162],
        [ 50,  94, 117, ..., 156, 251,  24],
        [218, 232,  96, ..., 197, 233, 247]]])

#### shape

In [56]:
rand = np.random.randint(0,255,(3,28,28))
rand.shape

(3, 28, 28)

#### size
=> total elements

In [57]:
rand = np.random.randint(0,255,(3,28,28))
rand.size

2352

#### data type

In [59]:
rand = np.random.randint(0,255,(3,28,28),dtype='uint8')
rand.dtype

dtype('uint8')

In [64]:
rand = np.random.randint(0,255,(3,28,28))
rand = rand.astype(float)
rand.dtype

dtype('float64')

#### Array merge

In [68]:
arr1 = np.array([[1,2,3,4,5,6,7],[1,2,3,4,5,6,7]])
arr2 = np.array([[1,2,3,4,5,6,7],[1,2,3,4,5,6,7]])
arr = arr1+arr2
arr

array([[ 1,  4,  9, 16, 25, 36, 49],
       [ 1,  4,  9, 16, 25, 36, 49]])

In [72]:
arr1 = np.array([[1,2,3,4,5,6,7],[1,2,3,4,5,6,7]])
arr = arr1+20
arr

array([[21, 22, 23, 24, 25, 26, 27],
       [21, 22, 23, 24, 25, 26, 27]])

In [73]:
arr1 = np.array([[1,2,3,4,5,6,7]])
arr2 = np.array([[1,2,3,4,5,6,7]])
arr = arr1-arr2
arr

array([[0, 1, 2, 3, 4, 5, 6]])

In [74]:
arr1 = np.array([[1,2,3,4,5,6,7]])
arr = arr1-1
arr

array([[0, 1, 2, 3, 4, 5, 6]])

In [70]:
arr1 = np.array([[1,2,3,4,5,6,7]])
arr2 = np.array([[1,2,3,4,5,6,7]])
arr = arr1*arr2
arr

array([[ 1,  4,  9, 16, 25, 36, 49]])

In [75]:
arr1 = np.array([[1,2,3,4,5,6,7]])
arr = arr1*5
arr

array([[ 5, 10, 15, 20, 25, 30, 35]])

In [71]:
arr1 = np.array([[1,2,3,4,5,6,7]])
arr2 = np.array([[1,2,3,4,5,6,7]])
arr = arr1/arr2
arr

array([[1., 1., 1., 1., 1., 1., 1.]])

In [76]:
arr1 = np.array([[1,2,3,4,5,6,7]])
arr = arr1/5
arr

array([[0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4]])