In [338]:
import numpy as np
print(np.__version__)

1.22.1


In [339]:
import cv2

In [340]:
def show_img(img,name='img'):
    cv2.imshow(name,img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

#### single row

In [341]:
arr_1row = np.array([1,2,3,4,5,6,7])
arr_1row

array([1, 2, 3, 4, 5, 6, 7])

#### multiple cols

In [342]:
arr_nd_col = np.array([[1,2],[2,2],[3,2]])
arr_nd_col

array([[1, 2],
       [2, 2],
       [3, 2]])

1d Array

In [343]:
arr_1d = np.array([1,2,3,4,5,6,7])
arr_1d

array([1, 2, 3, 4, 5, 6, 7])

#### 2d Array

In [344]:
arr_2d = np.array([[1,2,3,4,5,6,7],[1,2,3,4,5,6,7]])
arr_2d

array([[1, 2, 3, 4, 5, 6, 7],
       [1, 2, 3, 4, 5, 6, 7]])

#### multi dimension

In [345]:
arr_nd = np.array([
    [(1,2,3),(4,5,6,7)],
    [(1,2,3,4),(5,6,7)],
    [(1,2,3),(4,5,6,7)],
    [(1,2,3,4),(5,6,7)],
    [(1,2,3),(4,5,6,7)],
    [(1,2,3,4),(5,6,7)]], dtype=object)
arr_nd

array([[(1, 2, 3), (4, 5, 6, 7)],
       [(1, 2, 3, 4), (5, 6, 7)],
       [(1, 2, 3), (4, 5, 6, 7)],
       [(1, 2, 3, 4), (5, 6, 7)],
       [(1, 2, 3), (4, 5, 6, 7)],
       [(1, 2, 3, 4), (5, 6, 7)]], dtype=object)

#### Zeros

In [346]:
zeroes = np.zeros((3,3), dtype='uint8')
zeroes

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=uint8)

#### Ones

In [347]:
ones = np.ones((3,3), dtype='uint8')
ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=uint8)

#### Full

In [348]:
full = np.full((3,3),5, dtype='uint8')
full

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]], dtype=uint8)

#### eye

In [349]:
eye = np.eye(5, dtype='uint8')
eye

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=uint8)

#### Random

In [350]:
range = np.arange(1,100,1,dtype='uint8')
range

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
      dtype=uint8)

#### Line Space

In [351]:
line_space = np.linspace(0,100,10)
line_space

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

#### Random

In [352]:
rand = np.random.rand()
rand

0.10481801027667181

In [353]:
rand = np.random.rand(2,5)
rand

array([[6.36033204e-01, 9.41863486e-02, 9.70584508e-01, 1.81007185e-01,
        1.01348004e-01],
       [9.71012958e-02, 2.55458998e-04, 3.40457672e-01, 6.89921083e-01,
        2.60866176e-01]])

In [354]:
rand = np.random.rand(2,3,4)
rand

array([[[0.65718551, 0.33493456, 0.38957859, 0.24075191],
        [0.9795278 , 0.37052937, 0.83857803, 0.05236312],
        [0.14599527, 0.56060695, 0.95009218, 0.47240762]],

       [[0.25365508, 0.92332142, 0.64044768, 0.66347859],
        [0.3865276 , 0.63037579, 0.83854132, 0.1020809 ],
        [0.89634026, 0.52176849, 0.36825032, 0.16876264]]])

with in range 100

In [355]:
rand = np.random.rand()*100
rand

40.63585729782662

In [356]:
rand = np.random.rand(2,3,4)*100
rand

array([[[35.32858474, 67.85910421, 55.23954336, 87.25923955],
        [19.82839187, 32.39502192, 45.93599984, 25.74233311],
        [25.8472445 , 63.40661533, 80.78425691, 30.35954732]],

       [[40.91161024, 59.5267111 , 57.29588473, 33.4953795 ],
        [27.43081925, 70.33980596, 88.57327823,  7.77608396],
        [66.59671574, 86.94379193, 86.49358303, 17.39802454]]])

In [357]:
rand = np.random.randint(0,255,(3,28,28))
rand

array([[[ 17, 198, 156, ..., 137, 148, 189],
        [169, 205,  40, ..., 186, 140,   3],
        [246, 155, 148, ..., 205,  21, 212],
        ...,
        [131, 210,  68, ..., 190, 159, 228],
        [178,  87,  12, ...,  99, 246, 239],
        [138, 160,  41, ..., 138, 114, 110]],

       [[ 76, 146,  57, ..., 225,  53, 181],
        [240, 154, 233, ...,   7,  46,  10],
        [ 60, 158, 241, ...,  64,  91, 223],
        ...,
        [211, 162, 169, ..., 151,   4, 103],
        [213,  93,  49, ...,  52,  63,   3],
        [115,  66, 236, ...,  56,  40,   9]],

       [[134, 135, 193, ...,  68, 198,  29],
        [ 90,  90, 146, ...,  21, 186, 157],
        [165, 216,  84, ...,  25, 213,  56],
        ...,
        [ 92,  47, 236, ..., 218,  46, 239],
        [245, 244,  72, ..., 114, 139, 254],
        [  4,   8, 204, ..., 185,  79,  25]]])

#### shape

In [358]:
rand = np.random.randint(0,255,(3,28,28))
rand.shape

(3, 28, 28)

#### size
=> total elements

In [359]:
rand = np.random.randint(0,255,(3,28,28))
rand.size

2352

#### data type

In [360]:
rand = np.random.randint(0,255,(3,28,28),dtype='uint8')
rand.dtype

dtype('uint8')

In [361]:
rand = np.random.randint(0,255,(3,28,28))
rand = rand.astype(float)
rand.dtype

dtype('float64')

#### Array merge

In [362]:
arr1 = np.array([[1,2,3,4,5,6,7],[1,2,3,4,5,6,7]])
arr2 = np.array([[1,2,3,4,5,6,7],[1,2,3,4,5,6,7]])
arr = arr1+arr2
arr

array([[ 2,  4,  6,  8, 10, 12, 14],
       [ 2,  4,  6,  8, 10, 12, 14]])

In [363]:
arr1 = np.array([[1,2,3,4,5,6,7],[1,2,3,4,5,6,7]])
arr = arr1+20
arr

array([[21, 22, 23, 24, 25, 26, 27],
       [21, 22, 23, 24, 25, 26, 27]])

In [364]:
arr1 = np.array([1,2,3,4,5,6,7])
arr2 = np.array([1,2,3,4,5,6,7])
arr = arr1-arr2
arr

array([0, 0, 0, 0, 0, 0, 0])

In [365]:
arr1 = np.array([1,2,3,4,5,6,7])
arr = arr1-4
arr

array([-3, -2, -1,  0,  1,  2,  3])

In [366]:
arr1 = np.array([1,2,3,4,5,6,7])
arr2 = np.array([1,2,3,4,5,6,7])
arr = arr1*arr2
arr

array([ 1,  4,  9, 16, 25, 36, 49])

In [367]:
arr1 = np.array([1,2,3,4,5,6,7])
arr = arr1*5
arr

array([ 5, 10, 15, 20, 25, 30, 35])

In [368]:
arr1 = np.array([1,2,3,4,5,6,7])
arr2 = np.array([1,2,3,4,5,6,7])
arr = arr1/arr2
arr

array([1., 1., 1., 1., 1., 1., 1.])

In [369]:
arr1 = np.array([1,2,3,4,5,6,7])
arr = arr1/5
arr

array([0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4])

#### Min-Max

In [370]:
arr = np.array([1,2,3,4,5,6,7])
arr.min()

1

In [371]:
arr = np.array([1,2,3,4,5,6,7])
arr.max()

7

#### indexing

In [372]:
arr = np.array([1,2,3,4,5,6,7])
arr[2]

3

In [373]:
arr = np.array([[1,2,3,4,5,6,7],[1,2,3,4,5,6,7]])
arr[:,2]

array([3, 3])

In [374]:
arr = np.array([[1,2,3,4,5,6,7],[1,2,3,4,5,6,7]])
arr[1,:]

array([1, 2, 3, 4, 5, 6, 7])

In [375]:
arr = np.array([[1,2,3,4,5,6,7],[1,2,3,4,5,6,7]])
arr[1,4:]

array([5, 6, 7])

In [376]:
arr = np.array([[1,2,3,4,5,6,7],[1,2,3,4,5,6,7]])
arr[1,2:4]

array([3, 4])

In [377]:
arr = np.array([1,2,3,4,5,6,7])
arr[2:4]

array([3, 4])

#### Reverse

In [378]:
arr = np.array([1,2,3,4,5,6,7])
arr[::-1]

array([7, 6, 5, 4, 3, 2, 1])

#### Reshape

In [379]:
arr = np.array([[1,2,3,4,5,6,7],[1,2,3,4,5,6,7]])
print(arr.shape)
arr = arr.reshape(7,2)
arr

(2, 7)


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [380]:
arr = np.array([[1,2,3,4,5,6,7],[1,2,3,4,5,6,7]])
print(arr.shape)
arr = arr.reshape(14,1)
arr

(2, 7)


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [381]:
arr = np.array([[1,2,3,4,5,6,7],[1,2,3,4,5,6,7]])
print(arr.shape)
arr = arr.reshape(14)
arr

(2, 7)


array([1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7])

#### Append

In [382]:
arr = np.array([[1,2,3,4,5,6,7],[1,2,3,4,5,6,7]])
arr = np.append(arr,80)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  1,  2,  3,  4,  5,  6,  7, 80])

#### Delete

In [383]:
arr = np.array([[1,2,3,4,5,6,7],[1,2,3,4,5,6,7]])
arr = np.delete(arr,1)
arr

array([1, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7])

#### Flatten

In [384]:
arr = np.array([[1,2,3,4,5,6,7],[1,2,3,4,5,6,7]])
arr = arr.ravel()
arr

array([1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7])

In [385]:
arr = np.array([[1,2,3,4,5,6,7],[1,2,3,4,5,6,7]])
arr = arr.flatten()
arr

array([1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7])

In [386]:
rand = np.random.randint(0,255,(3,28,28))
print(rand.shape)
rand  = rand.flatten()
print(rand.shape)
rand

(3, 28, 28)
(2352,)


array([194,  11, 210, ..., 200, 152,  93])

#### Concatenation

In [387]:
arr1 = np.array([1,2,3,4,5,6,7])
arr2 = np.array([1,2,3,4,5,6,7])
arr = np.concatenate((arr1,arr2))
arr

array([1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7])

#### transpose
rows to cols cols to rows

In [388]:
arr = np.array([[1,2,3],[4,5,6]])
arr.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

#### Copy

In [389]:
arr = np.array([[1,2,3],[4,5,6]])
arr_copy = arr
arr_copy

array([[1, 2, 3],
       [4, 5, 6]])

In [390]:
arr = np.array([[1,2,3],[4,5,6]])
arr_copy = np.copy(arr)
arr_copy

array([[1, 2, 3],
       [4, 5, 6]])

#### Simple Image

In [402]:
img = np.zeros((300,300))
img[:,:]=100
img = img[:,:]+10
img[50:250,50:250] = 255
# show_img(img)
cv2.imwrite('sample.jpg',img)

True